### ISSUE TITLE
Google Calendar API

### ISSUE THREAD

**Issue by ILikeTeaALot** [Gum-Joe/isitweeka#1]
There's better ways to get the Google api. I'm fairly certain there's a node module for it. I'm happy to help with this over the holidays if you'd like (also, permission to make a novelty app?)

**Comment by Gum-Joe** [comment]
So I did download the node apio (`googleapis`).... and it didn't compile (because it's designed for Node.js, NOT vanilla JS, it uses Node.js libs like http2 and not `fetch`, hence why it doesn't work`)


But, since you offered, I'll open a feature tracker branch with the stuff I want to implement.

Also yes, you can make a novelty app - if you want I'll open up the repo to you so you can add a PR so everything is in this repo

**Comment by Gum-Joe** [comment]
Actually, this is the perfect opportunity to use GH Projects?
Thoughts?

**Comment by ILikeTeaALot** [comment]
having the app in the same repo _might_ be quite a good idea

**Comment by ILikeTeaALot** [comment]
> Actually, this is the perfect opportunity to use GH Projects?
> 
> Thoughts?

also yes

**Comment by Gum-Joe** [comment]
Added as collaborator
Check email for invite.

**Comment by Gum-Joe** [comment]
iCal: https://calendar.google.com/calendar/ical/calendar%40camphillboys.bham.sch.uk/public/basic.ics

**Comment by ILikeTeaALot** [comment]
KECHG iCal: https://calendar.google.com/calendar/ical/calendar%40kechg.org.uk/public/basic.ics (hopefully)
